#!/usr/bin/env ruby

docker_repository = "stodevx/stograde"

tag = ARGV[0]

LINE_HEADER = ">>>>"
OUTPUT_LINE_HEADER = "#{LINE_HEADER}  -"

image_name = "#{docker_repository}:#{tag}"

puts "#{LINE_HEADER} Building #{image_name}... (This is gonna take a bit. You'll get logs, just be patient.)"

output = `docker build -t #{image_name} .`

puts output.split(/$/).join("\n#{OUTPUT_LINE_HEADER} ").gsub("\r","\r#{OUTPUT_LINE_HEADER} ")

docker_username = ENV['DOCKER_USERNAME']
docker_password = ENV['DOCKER_PASSWORD']

# If docker_username or docker_password exists, use those to log in
if !!docker_username && !!docker_password
	puts "#{LINE_HEADER} Logging into Docker Hub..."
	`docker login -u='#{docker_username}' -p='#{docker_password}' >/dev/null 2>&1`
	puts "#{LINE_HEADER} Successfully logged in!"
end

puts "#{LINE_HEADER} Pushing to Docker Hub..."

output = `docker push #{image_name}`

puts output.split(/$/).join("\n#{OUTPUT_LINE_HEADER} ").gsub("\r","\r#{OUTPUT_LINE_HEADER} ")

puts "#{LINE_HEADER} Done!"
