#!/usr/bin/env fish

# hwNum – username
set hw $argv[1]
set user $argv[2]
echo "# $hw – $user"
set cwd (pwd)

for file in *.cpp
	echo "### $file"
	echo "**contents of $file**"
	echo
	cat $file | sed 's/^/    /'
	echo
	echo "**warnings about $file**"
	echo
	g++-4.8 --std=c++11 $file -o $file.exec 2>| sed 's/^/    /'
	echo
	echo "**results of $file**"
	echo
	echo '```'
	~/cs251/_scripts/run-file $hw $cwd/$file.exec 2>| sed 's/^/    /'
	echo '```'
	echo
	rm -f $file.exec
end
