#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))

require 'script'

DOCKER_TAG_REGEXP = /([\w\.\/]+):?([\w\.\/]+)?/

tags = ARGV.grep(DOCKER_TAG_REGEXP)

tags.each_with_index do |tag, tag_index|
	command = ['docker', 'build', '-t', "#{tag}", '.']

	puts "Building tag #{tag_index + 1}/#{tags.count} #{tag}"

	puts "Running `#{command.join(' ')}`..."
	Runner.run(command) do |output_line|
		puts output_line.chomp
	end
end
