#!/bin/bash
set -ev

if latest_tag=`git describe --abbrev=0 --tags HEAD 2>&1`;
then
    >&2 echo "latest: $latest_tag"
else
    >&2 echo "no latest"
fi

if on_tag=`git describe --exact-match --tags HEAD 2>/dev/null`;
then
    >&2 echo "on: $on_tag"
else
    >&2 echo "not on"
fi

if branch=`git rev-parse --abbrev-ref HEAD`;
then
    >&2 echo "branch: $branch"
else
    >&2 echo "no branch"
fi

if [[ "${branch}" == "HEAD" ]];
then
    if [ -z "$on_tag" ];
    then
        echo "HEAD"
    else
        echo "$on_tag"
    fi
else
    if [[ "${branch}" == "master" ]];
    then
        echo "HEAD"
    else
        echo "$branch"
    fi
fi
