#!/bin/sh

>&2 echo "env: `env`"

if [ -z "$TRAVIS_TAG" ];
then

    if [ "$TRAVIS_BRANCH" = "master" ];
    then
        if [ "$TRAVIS_PULL_REQUEST" = "false" ];
        then
            >&2 echo "commit to master, building HEAD tag..."
            echo "HEAD"
        else
            >&2 echo "commit to master but this is a PR. let's not get ahead of ourselves."
        fi
    else
        >&2 echo "commit to branch other than master. whatever, dude."
    fi

else

    >&2 echo "building a tag."
    echo "$TRAVIS_TAG"

fi
